version: "3.1"
services:
  spring:
    image: yaswanthreddy1007/dockerswarm:TAG
    ports:
    - 8080:8080
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=yaswanth
    - MONGO_DB_PASSWORD=yaswanth968
    networks:
    - yaswanth
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=yaswanth
    - MONGO_INITDB_ROOT_PASSWORD=yaswanth968
    networks:
    - yaswanth
    volumes:
    - gagana:data/db

networks:
  yaswanth:
    driver: overlay

volumes:
  gagana:
    driver: local
