version: "3"

networks:
  gova:
    driver: bridge
volumes:
  gova:
    driver: local
services:
  spring:
    image: yaswanthreddy1007/database1:4
    depends_on:
    - mongo
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=yaswanth
    - MONGO_DB_PASSWORD=yaswanth968
    ports: 
    - 9000:8080
    networks: 
    - gova

  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=yaswanth
    - MONGO_INITDB_ROOT_PASSWORD=yaswanth968
    networks:  
    - gova
    volumes: 
    - gova:/data/db
