apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: test-ns
spec:
  selector:
    matchLabels:
      team: production  
  template:
    metadata:
      labels:
        team: production   
    spec:
      containers:
      - name: mongodbcontainer
        image: mongo
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: yaswanth
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: yaswanth968
        resources:
          requests:
            cpu: "100m"
            memory: "252Mi"
          limits:
            memory: "500Mi"
            cpu: "200m"
        ports:
        - containerPort: 27017
        
---
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
  namespace: test-ns
spec:
  selector:
    team: production
  ports:
  - port: 27017
    targetPort: 27017
